SYNTHETIC_EMPLOYERS: list[dict] = [
    {
        "employer": "Google LLC",
        "matcher": "Vanguard",
        "advizorpro": "Vanguard",
        "aliases": ["google", "alphabet", "alphabet inc"],
        "matcher_confidence": 1.0,
        "matcher_label": "High",
    },
    {"employer": "Amazon.com Services LLC", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "Walmart Inc", "matcher": "Merrill Lynch", "advizorpro": "Merrill Lynch", "aliases": ["walmart"]},
    {"employer": "Amazon", "matcher": "Fidelity", "advizorpro": "Fidelity", "aliases": ["amazon"]},
    {
        "employer": "Citi",
        "matcher": "Alight Solutions",
        "advizorpro": "Alight Solutions",
        "aliases": ["citigroup", "citigroup inc"],
    },
    {
        "employer": "Goldman Sachs",
        "matcher": "Alight Solutions",
        "advizorpro": "Alight Solutions",
        "aliases": ["goldman sachs group"],
    },
    {"employer": "Uncovered Demo Corp", "matcher": "Paychex", "advizorpro": "Paychex"},
    {
        "employer": "Target Corporation",
        "matcher": "Alight Solutions",
        "advizorpro": "Alight Solutions",
        "aliases": ["target"],
        "matcher_confidence": 1.0,
        "matcher_label": "High",
    },
    {
        "employer": "Costco Wholesale Corporation",
        "matcher": "Fidelity",
        "advizorpro": "Fidelity",
        "aliases": ["costco", "costco wholesale"],
    },
    {"employer": "Home Depot USA Inc", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "FedEx Corporation", "matcher": "Vanguard", "advizorpro": "Vanguard"},
    {"employer": "UPS Inc", "matcher": "Empower", "advizorpro": "Empower"},
    {"employer": "Starbucks Corporation", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "Nike Inc", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "Coca-Cola Company", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "PepsiCo Inc", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "Johnson & Johnson", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "Procter & Gamble", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "General Electric", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "Boeing Company", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "Lockheed Martin", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "Raytheon Technologies", "matcher": "Fidelity", "advizorpro": "Fidelity"},
    {"employer": "Acme Robotics Inc", "matcher": "Empower", "advizorpro": None},
    {"employer": "Blue Harbor Logistics", "matcher": "Vanguard", "advizorpro": None},
    {"employer": "Cedar Peak Manufacturing", "matcher": "Voya", "advizorpro": None},
    {"employer": "Delta Trail Foods", "matcher": "Empower", "advizorpro": None},
    {"employer": "Echo Valley Health", "matcher": "Fidelity", "advizorpro": None},
    {"employer": "Frostline Analytics", "matcher": None, "advizorpro": "Fidelity"},
    {"employer": "Granite Ridge Staffing", "matcher": None, "advizorpro": "Empower"},
    {"employer": "Harborview Clinics", "matcher": None, "advizorpro": "Vanguard"},
    {"employer": "Ironclad Security Group", "matcher": None, "advizorpro": "Voya"},
    {"employer": "Jetstream Airlines", "matcher": "Empower", "advizorpro": "Fidelity"},
    {"employer": "Kestrel Biotech", "matcher": "Vanguard", "advizorpro": "Empower"},
    {"employer": "Northwind Traders", "matcher": None, "advizorpro": None},
    {"employer": "Pinnacle Sports LLC", "matcher": None, "advizorpro": None},
]
