/** Auto-generated by scripts/generate-demo-playbook-steps.py — do not edit. */
export const PLAYBOOK_DATA = {
  "portalMenuHints": [
    "Withdrawals",
    "Rollovers",
    "Distributions",
    "Transfer Out",
    "Move Money",
    "Take a Withdrawal"
  ],
  "destinationHints": [
    "Other",
    "Add My Own",
    "Other Provider",
    "Custom Provider",
    "Not Listed",
    "Manual Entry"
  ],
  "general": {
    "online": [
      "Log in to the old 401(k) provider's website (not the employer's HR site).",
      "Open Withdrawals, Rollovers, or Distributions.",
      "Choose rollover to another retirement account (direct rollover).",
      "For receiving provider, choose Other / Add My Own / Not Listed and enter PensionBee.",
      "When prompted for check payable-to, enter: PensionBee FBO [your name].",
      "Mailing address: PO Box 72, New York, NY 10272.",
      "Pre-tax funds \u2192 Traditional IRA account number. Roth funds \u2192 Roth IRA account number.",
      "Mixed pre-tax and Roth \u2192 two separate checks, one per account type.",
      "Submit the request and capture the confirmation screen."
    ],
    "phone": [
      "Confirm your identity and request a direct rollover distribution.",
      "When asked for the receiving provider, say PensionBee.",
      "When asked how to make the check payable, say: PensionBee FBO [your name].",
      "When asked for the mailing address, say: PO Box 72, New York, NY 10272.",
      "Confirm pre-tax vs Roth routing if asked (pre-tax \u2192 Traditional IRA, Roth \u2192 Roth IRA)."
    ],
    "forms": [
      {
        "label": "Check payable to",
        "instruction": "PensionBee FBO [your name]"
      },
      {
        "label": "Mailing address",
        "instruction": "PO Box 72, New York, NY 10272"
      }
    ]
  },
  "providers": {
    "Alight Solutions": {
      "online": [
        "Go to alight.com/find-your-hr-website and click Find Your HR Website.",
        "Search for your employer name and open their benefits website.",
        "Log on with your username and password (your login page may look different).",
        "Click Savings & Retirement.",
        "Click Withdrawals and Rollovers Out.",
        "Click here to add a Rollover account (financial institutions section).",
        "When RolloverCentral opens in a new tab, click Get Started.",
        "Accept Terms & Conditions and click Continue.",
        "Fill Age, Account Balance, Email, set Have an existing IRA to Yes, then Get Started.",
        "Next to Add Your Rollover to an Existing IRA, click Go.",
        "Select PensionBee as your IRA provider.",
        "Click the link to pensionbee.com/us/beehive/transfer/rollover-central and log in to get your 14-digit VAN.",
        "Enter your PensionBee VAN in IRA Account Number and Confirm IRA Account Number.",
        "Select IRA Account Type, when you opened the account, and your rollover reason; click Continue.",
        "Click Continue, close RolloverCentral, and return to the Alight site.",
        "Go to Savings \u2192 Withdrawals and Rollovers Out and verify the PensionBee account number under Rollover to Institution.",
        "Confirm account details match PensionBee and proceed.",
        "Return to Savings \u2192 Withdrawals and Rollovers Out.",
        "Click Get Started next to Total Distribution or Partial Distribution.",
        "Select Roll Over an Amount to an IRA or Another Employer's Plan.",
        "Select IRA as account type and click Continue.",
        "Acknowledge the $25 processing fee and click Continue.",
        "Choose All of the Cash Available or Specific Amount, then Continue.",
        "Review Your Total Payment and click Continue.",
        "Tick the Acknowledgement box and click Continue.",
        "Under destination, select Direct Rollover (electronic transfer to UMB, 2\u20133 business days).",
        "Click Continue, review Destination for Cash Rollover, and click Submit.",
        "Complete MFA \u2014 Text Me a Code or Call Me With a Code, select your phone, enter the code.",
        "Capture the confirmation screen and send it to PensionBee via BeeHive chat or info@pensionbee.com (subject: Your Name + Alight + Rollover Confirmation)."
      ],
      "phone": [
        "Confirm identity and request a direct rollover distribution to an external IRA.",
        "Say PensionBee is the receiving provider.",
        "When asked for check payable-to and mailing address, use your PensionBee rollover instructions (see copy chips or general guide)."
      ],
      "phoneIntro": "If you cannot complete the online RolloverCentral path, call and request a direct rollover to PensionBee. Use the general PensionBee payable and mailing instructions when asked.",
      "repQuestions": [
        {
          "question": "Pre-tax or Roth?",
          "answer": "Pre-tax \u2192 Traditional IRA. Roth \u2192 Roth IRA."
        },
        {
          "question": "Check payable to?",
          "answer": "PensionBee FBO [your name]"
        },
        {
          "question": "Mailing address?",
          "answer": "PO Box 72, New York, NY 10272"
        }
      ],
      "forms": [
        {
          "label": "IRA provider",
          "instruction": "PensionBee"
        },
        {
          "label": "IRA account number (VAN)",
          "instruction": "14-digit Virtual Account Number from BeeHive rollover-central \u2014 BeeKeeper provides if needed."
        },
        {
          "label": "Check payable to (if paper)",
          "instruction": "PensionBee FBO [your name]"
        },
        {
          "label": "Mailing address (if paper)",
          "instruction": "PO Box 72, New York, NY 10272"
        }
      ],
      "forwardStepRequired": false,
      "hasReconstructed": false
    },
    "Empower": {
      "online": [
        "Log in to the Empower participant portal.",
        "Locate the old 401(k) plan to roll over.",
        "Begin the rollover/distribution request and select a direct rollover.",
        "Set the destination as the PensionBee IRA (direct rollover; check payable per PensionBee instructions).",
        "Complete any required forms.",
        "Capture the confirmation screen. Confirm the check mails to the user's address; PensionBee sends a prepaid envelope to forward it.",
        "On receipt of the forwarded check, BeeKeeper applies it to the PensionBee IRA."
      ],
      "phone": [
        "Verify identity and confirm the plan you are rolling over.",
        "Request a direct rollover \u2014 check will mail to your address on file.",
        "Set expectation: you will forward the check to PensionBee using the prepaid envelope."
      ],
      "phoneIntro": "Call Empower and say you want a direct rollover from your old 401(k) to an external IRA.",
      "repQuestions": [
        {
          "question": "Pre-tax or Roth?",
          "answer": "Pre-tax \u2192 Traditional IRA. Roth \u2192 Roth IRA."
        },
        {
          "question": "Who should the check be payable to?",
          "answer": "Payable to PensionBee FBO [your name] \u2014 that keeps it a direct rollover. Mail it to my address on file; I'll forward it to PensionBee."
        }
      ],
      "forms": [
        {
          "label": "Distribution type",
          "instruction": "Direct rollover to external IRA."
        },
        {
          "label": "Receiving institution",
          "instruction": "Enter PensionBee as the receiving provider."
        },
        {
          "label": "Check destination",
          "instruction": "Check mails to YOU first \u2014 PensionBee sends a prepaid envelope to forward it."
        },
        {
          "label": "Notary",
          "instruction": "If notary is required, STOP \u2014 escalate to a BeeKeeper (virtual notary available)."
        }
      ],
      "forwardStepRequired": true,
      "hasReconstructed": false
    },
    "Fidelity": {
      "online": [
        "Log in to Fidelity NetBenefits.",
        "Locate the old 401(k) plan to roll over.",
        "Enter the rollover/withdrawal flow (under the withdrawals/loans area of the employer plan, not the retail account view).",
        "Select 'Express rollover to Fidelity' to route funds into a Fidelity Rollover IRA.",
        "Open the Fidelity Rollover IRA if one does not exist (pre-tax \u2192 Rollover/Traditional; Roth \u2192 Roth).",
        "Confirm the amount and complete the rollover into the Rollover IRA.",
        "Provide PensionBee the Fidelity Rollover IRA account info via Beehive chat to trigger the ACAT.",
        "PensionBee initiates the ACAT into the PensionBee IRA; BeeKeeper monitors until funds land."
      ],
      "phone": [
        "Confirm your identity (name, SSN, employer/plan).",
        "Request a direct rollover distribution to an external IRA.",
        "If Avenue 3 is available, prefer Express rollover to a Fidelity Rollover IRA instead of a check."
      ],
      "phoneIntro": "Call Fidelity NetBenefits and say you want to roll over your old 401(k) to an IRA.",
      "repQuestions": [
        {
          "question": "Pre-tax or Roth?",
          "answer": "Pre-tax \u2192 Traditional/Rollover IRA. Roth \u2192 Roth IRA. Mixed \u2192 two separate rollovers."
        },
        {
          "question": "Who should the check be payable to?",
          "answer": "Payable to PensionBee FBO [your name] \u2014 that keeps it a direct rollover. (Prefer the online Express rollover to avoid a check entirely.)"
        }
      ],
      "forms": [
        {
          "label": "Distribution type",
          "instruction": "Select direct rollover to another retirement account."
        },
        {
          "label": "Receiving institution",
          "instruction": "Other / Add My Own \u2014 enter PensionBee."
        },
        {
          "label": "Mailing address",
          "instruction": "PO Box 72, New York, NY 10272"
        },
        {
          "label": "Account type",
          "instruction": "Pre-tax \u2192 Traditional IRA number. Roth \u2192 Roth IRA number."
        }
      ],
      "forwardStepRequired": false,
      "hasReconstructed": false
    },
    "Merrill Lynch": {
      "online": [
        "Go to benefits.ml.com/Accounts/Home and log in to your Merrill account.",
        "Click your plan name under Employer Sponsored Plans.",
        "Click View your withdrawal and rollover options.",
        "Under Rollover to an IRA, click Start a Rollover.",
        "Under Withdrawal Type, select SEPARATED FROM SERVICE WITHDRAWAL.",
        "Under Rollover Amount, check Maximum for a full rollover, then Continue.",
        "Select Rollover to another financial institution, then Add another Institution.",
        "Under Rollover Account Type, select IRA.",
        "In Rollover Institution Name, type PensionBee.",
        "Enter your PensionBee account number from BeeHive (upper-right icon) \u2014 BeeKeeper can help if needed.",
        "Verify the address on file matches your current address and click Save. If wrong, call Merrill to update before proceeding.",
        "Read Merrill's notice and click Next.",
        "Under Delivery Selections, select Standard Mail and Continue.",
        "Review the 402(f) Tax Notice, enter your Benefits OnLine password, Submit, and send the confirmation screenshot to PensionBee (BeeHive or info@pensionbee.com \u2014 subject: Your Name + Merrill + Rollover Confirmation)."
      ],
      "phone": [
        "Confirm identity and request a direct rollover to an external IRA at PensionBee.",
        "Note the check will mail to your address on file \u2014 PensionBee will send a prepaid envelope to forward it.",
        "When asked for payable and mailing details, use PensionBee rollover instructions."
      ],
      "phoneIntro": "Call Merrill and request a direct rollover to PensionBee. If portal steps fail, use general PensionBee payable and mailing instructions.",
      "repQuestions": [
        {
          "question": "Pre-tax or Roth?",
          "answer": "Pre-tax \u2192 Traditional IRA. Roth \u2192 Roth IRA."
        },
        {
          "question": "Check payable to?",
          "answer": "PensionBee FBO [your name] (or payable to you if they mail to participant \u2014 forward to PensionBee)"
        },
        {
          "question": "Mailing address?",
          "answer": "Your address on file for participant delivery; forward to PO Box 72, New York, NY 10272"
        }
      ],
      "forms": [
        {
          "label": "Rollover institution",
          "instruction": "PensionBee"
        },
        {
          "label": "Account number",
          "instruction": "PensionBee IRA account number from BeeHive \u2014 route to BeeKeeper if needed."
        },
        {
          "label": "Check payable to",
          "instruction": "PensionBee FBO [your name]"
        }
      ],
      "forwardStepRequired": true,
      "hasReconstructed": false
    },
    "Principal": {
      "online": [
        "Go to accounts.principal.com and click Log in.",
        "Enter your username and click Next.",
        "Enter your password and click Verify.",
        "From your 401(k) overview, click Rollovers, then Rollover IRA.",
        "Under Move outside Principal, click Learn more about an outside IRA.",
        "Click Start request to begin your rollover to PensionBee.",
        "Select Traditional pre-tax IRA or Roth IRA to match your funds, then Distribution details.",
        "Select Transfer the entire available amount, then Delivery options.",
        "Select Mailed directly to a financial institution, then Final review.",
        "Review rollover details including fees, then Submit.",
        "Accept disclosures, confirm today's date, and Submit request.",
        "Enter the phone verification code and click Verify.",
        "Save your request number and send the confirmation screenshot to PensionBee (BeeHive or info@pensionbee.com \u2014 subject: Your Name + Principal + Rollover Confirmation)."
      ],
      "phone": [
        "Confirm identity and request direct rollover to external IRA at PensionBee.",
        "Request check be mailed directly to PensionBee (financial institution).",
        "When asked for check payable-to and mailing address, use PensionBee rollover instructions."
      ],
      "phoneIntro": "Call Principal and request a direct rollover to PensionBee mailed to the financial institution. Use general PensionBee payable and mailing when asked.",
      "repQuestions": [
        {
          "question": "Pre-tax or Roth?",
          "answer": "Pre-tax \u2192 Traditional IRA. Roth \u2192 Roth IRA."
        },
        {
          "question": "Check payable to?",
          "answer": "PensionBee FBO [your name]"
        },
        {
          "question": "Mailing address?",
          "answer": "PO Box 72, New York, NY 10272"
        }
      ],
      "forms": [
        {
          "label": "Receiving institution",
          "instruction": "PensionBee"
        },
        {
          "label": "Check payable to",
          "instruction": "PensionBee FBO [your name]"
        },
        {
          "label": "Mailing address",
          "instruction": "PO Box 72, New York, NY 10272"
        },
        {
          "label": "Processing timeline",
          "instruction": "Expect 7\u201310 business days for Principal to mail the check to PensionBee."
        }
      ],
      "forwardStepRequired": false,
      "hasReconstructed": false
    },
    "Vanguard": {
      "online": [
        "Navigate to the Vanguard login page and click 'Log In'.",
        "Enter username and password and log in (use 'Forgot your username or password?' or 'Set up online account access' if needed).",
        "Click 'Access my money', then 'Options if I leave my employer'.",
        "Scroll to 'After you leave your employer, what can you do with your money?' and click 'See what they are'.",
        "Select the rollover option and choose a direct rollover to an external IRA.",
        "Enter the PensionBee IRA destination details; set the check payable per PensionBee instructions, mailed directly to PensionBee where allowed.",
        "Confirm and capture the confirmation screen.",
        "On receipt of the direct check, BeeKeeper applies it to the PensionBee IRA."
      ],
      "phone": [
        "Confirm identity and the plan being rolled over.",
        "Request direct rollover \u2014 check mailed directly to PensionBee where allowed.",
        "Capture confirmation number and expected timeline."
      ],
      "phoneIntro": "Call Vanguard and request a direct rollover from your old 401(k) to an external IRA.",
      "repQuestions": [
        {
          "question": "Pre-tax or Roth?",
          "answer": "Pre-tax \u2192 Traditional IRA. Roth \u2192 Roth IRA."
        },
        {
          "question": "Mailing address for the check?",
          "answer": "PO Box 72, New York, NY 10272 \u2014 payable per PensionBee instructions."
        }
      ],
      "forms": [
        {
          "label": "Navigation",
          "instruction": "Access my money \u2192 Options if I leave my employer \u2192 direct rollover to external IRA."
        },
        {
          "label": "Receiving provider",
          "instruction": "Enter PensionBee destination details."
        },
        {
          "label": "Mailing address",
          "instruction": "PO Box 72, New York, NY 10272"
        }
      ],
      "forwardStepRequired": false,
      "hasReconstructed": false
    },
    "Voya": {
      "online": [
        "Log in to the Voya participant portal.",
        "Locate the old 401(k) plan to roll over.",
        "Begin the rollover/distribution request and select a direct rollover.",
        "Set the destination as the PensionBee IRA; check payable per PensionBee instructions, mailed directly to PensionBee where allowed.",
        "Complete any required forms.",
        "If the portal stalls pending phone verification, call Voya to confirm identity/intent before the check is released.",
        "Capture the confirmation screen.",
        "On receipt of the direct check, BeeKeeper applies it to the PensionBee IRA."
      ],
      "phone": [
        "Confirm identity and rollover intent (phone verification gate on some plans).",
        "Request direct rollover to PensionBee IRA \u2014 check mailed directly to PensionBee.",
        "Ask for expected check issuance timeline (Voya can be slower than peers)."
      ],
      "phoneIntro": "Call Voya to request a direct rollover \u2014 some plans require phone verification before the check releases.",
      "repQuestions": [
        {
          "question": "Pre-tax or Roth?",
          "answer": "Pre-tax \u2192 Traditional IRA. Roth \u2192 Roth IRA."
        },
        {
          "question": "Mailing address?",
          "answer": "PO Box 72, New York, NY 10272"
        }
      ],
      "forms": [
        {
          "label": "Distribution type",
          "instruction": "Direct rollover to external IRA."
        },
        {
          "label": "Destination",
          "instruction": "PensionBee \u2014 PO Box 72, New York, NY 10272"
        },
        {
          "label": "Phone verification",
          "instruction": "If portal stalls, call Voya to confirm identity before the check releases."
        }
      ],
      "forwardStepRequired": false,
      "hasReconstructed": false
    }
  },
  "demoAliases": {
    "Alight": "Alight Solutions",
    "Merrill Lynch": "Merrill Lynch"
  }
} as const;
