#!/usr/bin/env python3
"""Generate demo engine playbook steps from rollover-companion knowledge layer."""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
KNOWLEDGE = ROOT / "rollover-companion" / "rollover-knowledge-layer"
OUT = ROOT / "web" / "src" / "lib" / "demoEngine" / "playbookSteps.ts"

_FRONT_MATTER = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)

# Demo UI provider labels → canonical knowledge provider keys
DEMO_ALIASES: dict[str, str] = {
    "Alight": "Alight Solutions",
    "Merrill Lynch": "Merrill Lynch",
}


def parse_front_matter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    match = _FRONT_MATTER.match(text)
    if not match:
        raise ValueError(f"No front matter in {path}")
    return yaml.safe_load(match.group(1)) or {}


def step_texts(items: list[dict] | None) -> list[str]:
    return [str(s.get("text", "")).strip() for s in (items or []) if s.get("text")]


def form_steps(items: list[dict] | None) -> list[dict[str, str]]:
    out: list[dict[str, str]] = []
    for field in items or []:
        label = str(field.get("label", "")).strip()
        instruction = str(field.get("instruction", "")).strip()
        if label or instruction:
            out.append({"label": label or "Field", "instruction": instruction or label})
    return out


def main() -> None:
    general = parse_front_matter(KNOWLEDGE / "General_Rollover_Guide.md")
    portal_menu_hints = general.get("portal_menu_aliases") or []
    destination_hints = general.get("destination_dropdown_aliases") or []
    general_online = step_texts(general.get("general_steps"))
    general_phone = step_texts((general.get("general_call_script") or {}).get("steps"))
    general_forms = form_steps((general.get("general_form_guidance") or {}).get("fields"))

    providers: dict[str, dict] = {}
    for path in sorted(KNOWLEDGE.glob("*_Rollover_Guide.md")):
        if path.name == "General_Rollover_Guide.md":
            continue
        data = parse_front_matter(path)
        name = data.get("provider")
        if not name:
            continue
        cs = data.get("call_script") or {}
        fg = data.get("form_guidance") or {}
        providers[name] = {
            "online": step_texts(data.get("steps")),
            "phone": step_texts(cs.get("steps")),
            "phoneIntro": str(cs.get("intro") or ""),
            "portal": str(data.get("portal") or ""),
            "mechanism": str(data.get("mechanism") or ""),
            "checkDestination": str(data.get("check_destination") or ""),
            "repQuestions": [
                {"question": q.get("question", ""), "answer": q.get("answer", "")}
                for q in cs.get("rep_questions") or []
                if q.get("question")
            ],
            "forms": form_steps(fg.get("fields")),
            "forwardStepRequired": bool(data.get("forward_step_required")),
            "hasReconstructed": any(
                str(s.get("source_status", "")).lower() == "reconstructed"
                for s in (data.get("steps") or [])
            ),
        }

    payload = {
        "portalMenuHints": portal_menu_hints,
        "destinationHints": destination_hints,
        "general": {
            "online": general_online,
            "phone": general_phone,
            "forms": general_forms,
        },
        "providers": providers,
        "demoAliases": DEMO_ALIASES,
    }

    OUT.write_text(
        "/** Auto-generated by scripts/generate-demo-playbook-steps.py — do not edit. */\n"
        f"export const PLAYBOOK_DATA = {json.dumps(payload, indent=2)} as const;\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({len(providers)} providers)")


if __name__ == "__main__":
    main()
